-- ========================================================================================
-- This query answers the 4 business questions that will provide Kasi Mart with insights.
-- Table aliases used in the queries:
-- Customers = A
-- Products = B
-- Orders = C
-- ========================================================================================

-- Question 1:
-- Every order joined to customer name, product name, category, and a calculated line_revenue (quantity times unit_price).

-- Explanation:
-- This query shows the Kasi Mart manager the names of the customers who made the 150 orders,
-- the products they bought, and the categories those products fall under. It also shows
-- the quantity bought for each transaction, the price of each product, and the total revenue
-- generated from the quantity purchased in each transaction.
-- This matters because it gives the manager a clear view of what was bought, by whom, and how much each transaction generated.

SELECT C.order_id,
       A.customer_name,
       B.product_name,
       B.category,
       C.quantity,
       B.unit_price,
       C.quantity * B.unit_price AS line_revenue
FROM de_project_01.kasi_mart.orders C
INNER JOIN de_project_01.kasi_mart.customers A
ON C.customer_id = A.customer_id
INNER JOIN de_project_01.kasi_mart.products B
ON C.product_id = B.product_id
ORDER BY C.order_id;


-- Question 2:
-- Total revenue per customer.

-- Explanation:
-- This query shows the total revenue generated by each customer, regardless
-- of which product or product category they purchased and when the transactions
-- took place. This matters because it helps the Kasi Mart manager identify
-- their highest-value customers. This information can be used for targeted
-- advertising, customer loyalty strategies, and providing high-value customers
-- with premium customer service or special offers and subscriptions.

SELECT A.customer_id,
       A.customer_name,
       SUM(C.quantity * B.unit_price) AS total_revenue
FROM de_project_01.kasi_mart.orders C
INNER JOIN de_project_01.kasi_mart.customers A
ON C.customer_id = A.customer_id
INNER JOIN de_project_01.kasi_mart.products B
ON C.product_id = B.product_id
GROUP BY A.customer_id,
         A.customer_name
ORDER BY total_revenue DESC;


-- Question 3
-- Total revenue per product category.

-- Explanation:
-- This query shows the total revenue generated by each product category,
-- regardless of which customer purchased the products or when the transactions took place.
-- This matters because it helps the Kasi Mart manager understand which product categories are generating the most revenue.
-- This can help the business make better decisions about which categories to focus on, promote, keep in stock, or potentially expand.

SELECT B.category,
       SUM(C.quantity * B.unit_price) AS total_revenue
FROM de_project_01.kasi_mart.orders C
INNER JOIN de_project_01.kasi_mart.products B
ON C.product_id = B.product_id
GROUP BY B.category
ORDER BY total_revenue DESC;


-- Question 4:
-- Top 5 customers by total spend.

-- Explanation:
-- This query shows the top 5 customers based on the total amount they spent with Kasi Mart.
-- It takes all the transactions made by each customer,calculates their total spending, and then
-- ranks the customers from the highest spender to the lowest.
-- This matters because it helps the Kasi Mart manager identify their highest-value customers,
-- which can be useful for targeted advertising, customer loyalty programmes, special offers, and
-- providing these customers with a better customer experience.

SELECT A.customer_id,
       A.customer_name,
       SUM(C.quantity * B.unit_price) AS total_spend
FROM de_project_01.kasi_mart.orders C
INNER JOIN de_project_01.kasi_mart.customers A
ON C.customer_id = A.customer_id
INNER JOIN de_project_01.kasi_mart.products B
ON C.product_id = B.product_id
GROUP BY A.customer_id,
         A.customer_name
ORDER BY total_spend DESC
LIMIT 5;

